#ifndef DC_CONFIGDEF_H_
#define DC_CONFIGDEF_H_

enum DCConfigBool
{
    DC_CONFIG_TELEPORT_REMIND                  = 0,
    DC_CONFIG_TELEPORT_CHECK_REQ,
    DC_CONFIG_TELEPORT_CHECK_COST,
    DC_CONFIG_TELEPORT_CHECK_VISIBLE,
    DC_CONFIG_COMPOSE_CHECK_REQ,
    DC_CONFIG_COMPOSE_CHECK_COST,
    DC_CONFIG_ONLINE_REWARD_EXP,
    DC_CONFIG_ONLINE_REWARD_POINTS,

    DC_CONFIG_BOOL_COUNT
};

enum DCConfigFloat
{
    DC_CONFIG_FLOAT                            = 0,
    DC_CONFIG_DIFF_NORMAL,
    DC_CONFIG_DIFF_DUNGEON,
    DC_CONFIG_DIFF_RAID,

    DC_CONFIG_FLOAT_COUNT
};

enum DCConfigInt
{
    DC_CONFIG_TELEPORT_MENUITEMS_PER_PAGE      = 0,
    DC_CONFIG_COMPOSE_MENUITEMS_PER_PAGE,
    DC_CONFIG_COMPOSE_DEFAULT_LOOT_LIMIT,
    DC_CONFIG_COMPOSE_MAX_LOOT_LIMIT,
    DC_CONFIG_VIP_POINTS_ITEMENTRY,
    DC_CONFIG_VIP_START_VIPLEVEL,
    DC_CONFIG_VIP_START_POINTS,
    DC_CONFIG_ONLINE_REWARD_EXP_TIMER,
    DC_CONFIG_ONLINE_REWARD_EXP_COUNT,
    DC_CONFIG_ONLINE_REWARD_EXP_MINLEVEL,
    DC_CONFIG_ONLINE_REWARD_EXP_MAXLEVEL,
    DC_CONFIG_ONLINE_REWARD_POINTS_TIMER,
    DC_CONFIG_ONLINE_REWARD_POINTS_COUNT,
    DC_CONFIG_ONLINE_REWARD_POINTS_MINLEVEL,
    DC_CONFIG_ONLINE_REWARD_POINTS_MAXLEVEL,
    DC_CONFIG_MAX_PLAYER_TALENTS,

    DC_CONFIG_INT_COUNT
};

#endif